@startuml C1_Основное_решение_с_агентами
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title C1 — Система мониторинга животноводства

Person(Зоотехник, "Зоотехник", "Локальный мониторинг")
Person(админ, "Администратор", "Настройка системы")

' --- кажется, правильнее для C1 чтобы система была единой и одна. Но нам надо показать разницу Base/Alt ---
System_Boundary(животноводство, "Система мониторинга животноводства") {
    System(edge_агент, "Фермерский агент", "Edge-устройство с локальной обработкой")
    System(центральный_сервер, "Центральный сервер", "Агрегация, аналитика, управление")
}

' --- Существующие системы компании ---
System_Ext(kafka, "Брокер сообщений", "Apache Kafka")
System_Ext(erp, "ERP система", "1С:Агро")
System_Ext(веб_портал, "Веб-портал", "Общий портал")

System_Ext(камеры, "Камеры", "Видеонаблюдение")
System_Ext(кормушки, "Кормушки", "Автоматические")

Rel(Зоотехник, edge_агент, "Локальный мониторинг и оповещения")
Rel(админ, центральный_сервер, "Настройка и администрирование")

Rel(edge_агент, центральный_сервер, "Синхронизация данных")

Rel(центральный_сервер, kafka, "Публикация метрик")
Rel(центральный_сервер, erp, "Интеграция")
Rel(веб_портал, центральный_сервер, "Отображение данных")

Rel(edge_агент, камеры, "Получение видеопотока")
Rel(edge_агент, кормушки, "Управление")
@enduml
